apiVersion: v1
kind: Service
metadata:
  labels:
    version: 1
  name: hello-service
spec:
  ports:
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    deployment: hello-service