kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: config-assistant-be
  labels:
    {{- include "config-assistant-be-helm.labels" . | nindent 4 }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "config-assistant-be-helm.imageName" . }}
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: {{ .Values.build.output.kind }}
        name: {{ .Values.build.jvm.imageStreamTag.name }}
#        namespace: {{ .Values.build.jvm.imageStreamTag.namespace }}
  postCommit: {}
  source:
    type: Git
    git:
      uri: {{ .Values.build.jvm.git.url }}
      ref: {{.Values.build.jvm.git.refName }}
    contextDir: {{.Values.build.jvm.git.contextDir }}
  triggers:
    - type: ConfigChange
  runPolicy: Serial