apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "config-assistant-be-helm.fullname" . }}
  labels:
    app.kubernetes.io/part-of: {{ .Values.openshiftApplicationName }}
    {{- include "config-assistant-be-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "config-assistant-be-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "config-assistant-be-helm.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "config-assistant-be-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.container.image }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: http
            timeoutSeconds: 30
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: http
            timeoutSeconds: 30
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: ROUTE_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-assistant-cm
                  key: ROUTE_HTTP_PORT
            - name: ROUTE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: config-assistant-cm
                  key: ROUTE_DOMAIN
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
