apiVersion: v1
kind: Secret
metadata:
  name: {{ include "config-assistant-be-helm.fullname" . }}
  labels:
    {{- include "config-assistant-be-helm.labels" . | nindent 4 }}
stringData:
  tls.key: {{ .Values.credentials.tlsKey | b64enc }}
  tls.crt: {{ .Values.credentials.tlsCrt | b64enc }}
type: Opaque

